In [2]:
#numbers divided by four

fours = []
for num in range (50, 101):
    if num % 4 == 0:
        fours.append(num)
    else:
        pass
fours

[52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100]

enter your name: olu
enter your year_of_birth: 1960
hi olu, you are 64 years old

#  FINDINGS
1. that 2+2=4
2. that 2+2 is 4 everytime

In [11]:
NAME = 'PRINCESS'
AGE  = 27
HEIGHT = 187.5
STUDENT = False 
FRIENDS = ['ANITA', 'AMAKA']
NUMBER = {'1','2','3','4'}

print(type(NAME))
print(type(AGE))
print(type(HEIGHT))
print(type(STUDENT))
print(type(FRIENDS))
print(type(NUMBER))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'list'>
<class 'set'>

In [14]:
#write a program that prints hello world, this is your baby princess

print('hello world, this is your baby princess')

hello world, this is your baby princess

In [1]:
#write a program that accepts a username and greets them
name = input('enter your name: ')
print(f'hi,{name} welcome to Vetra')

enter your name: femi
hi,femi welcome to Vetra

In [2]:
#write a program that accepts a username and year of birth and returns their age
name = input('enter your name: ')
year = input('enter your birth_year: ')
year = int (year)
age = 2024 - year
print(f'hi,{name} you are {age} years old')

enter your name: femi
enter your birth_year: 2000
hi,femi you are 24 years old

#MATHEMATICAL OPERATORS

In [23]:
34.89 - 62.93

-28.04

In [24]:
1000 - 500

500

In [25]:
11/2

5.5

In [26]:
11//2

5

In [27]:
15%2

1

In [28]:
10%3

1

In [29]:
10%4

2

In [30]:
3**4

81

In [33]:
10**5

100000

In [34]:
1/10**3

0.001

In [44]:
27**(1/3)

3.0

In [42]:
3*FRIENDS

['ANITA', 'AMAKA', 'ANITA', 'AMAKA', 'ANITA', 'AMAKA']

In [45]:
9**0.5

3.0

In [50]:
#EXERCISES

1. #PROGRAMME THAT CALCULATES AREA OF THE RECTANGLE
length = int(input('Enter the value of length: '))
breadth = int(input('Enter the value of breadth: '))
area = length * breadth

print(f'The area of your rectangle is {area} cm squared')

Enter the value of length: 6
Enter the value of breadth: 7
The area of your rectangle is 42 cm squared

In [2]:
#write a programe that solves a quadratic equation


#accepting users input
a = int(input('Enter your value for a: '))
b = int(input('Enter your value for b: '))
c = int(input('Enter your value for c: '))

#define the solution

x1 = (-b + ((b**2) - (4*a*c)) ** (1/2)) /(2*a)
x2 = (-b - ((b**2) - (4*a*c)) ** (1/2)) /(2*a) 


print(f'The root of the equation is {x1} and {x2}')

Enter your value for a: 1
Enter your value for b: 5
Enter your value for c: 6
The root of the equation is -2.0 and -3.0

In [6]:
# write a program that returns the interest due on a loan and the amount payable

name = input('Welcome, enter your name: ')
principal = float(input('Enter the amount you want to borrow: '))
time = int(input('For how long: '))
rate = 5

interest = (principal * rate * time)/100

print(f'Hi {name}, the interest on N{principal} for {time} months is N{interest} at {rate}% per annum')
print('===========================================')
print(f'Total Amount Payables is {principal + interest} naira')

Welcome, enter your name: femi
Enter the amount you want to borrow: 100000
For how long: 12
Hi femi, the interest on N100000.0 for 12 months is N60000.0 at 5% per annum
===========================================
Total Amount Payables is 160000.0 naira

In [12]:
#Exercise
#write a program that calculates a person's tax and tithe by knowing their salary tax is 4%, tithe is 10%
#The program should return the amount they have paid in tax and tithe and what is left as their take home.

# assignment solution

salary = int(input('Enter your salary: '))
tax = salary * 0.04
tithe = salary * 0.1
# print(f'You paid ${tax} tax, ${tithe} tithe and you have ${salary - tithe - tax} left')
print(f'your salary is ${salary}, you paid ${tax} tax, ${tithe} tithe and you have $({(salary-tax)-tithe}) balance')

Enter your salary: 30000
your salary is $30000, you paid $1200.0 tax, $3000.0 tithe and you have $(25800.0) balance

In [17]:
#LESSON 2
#CONDITIONALS AND ITERABLES
# write a program that checks if someone is a child, adult, teenager or old

name = input('Enter your name: ')
year_of_birth = int(input(f'Hi {name}, enter your year of birth: '))
age = 2024 - year_of_birth

if age < 12:
    print(f'{name}, you are a child')
elif age < 20:
    print(f'{name}, you are a teenager')
elif age < 59:
    print(f'{name}, you are an adult')
else:
    print(f'{name}, you are a old')

Enter your name: femi
Hi femi, enter your year of birth: 1960
femi, you are a old

In [1]:
# write a program that outputs a student's admission eligibility. They can get into UI
# only if they score above 60 in english and mathematics. However they can get into Bowen
# with above 60 in at least one course

name = input('Enter your name: ')
english = int(input('English: '))
maths = int(input('Maths: '))

if english > 60 and maths > 60:
    print(f'Congrats {name}! you have gotten into UI')
elif english > 60 or maths > 60:
    print(f'HI {name} welcome to Bowen')
else:
    print(f'{name}!!! nawa!!')

Enter your name: femi
English: 55
Maths: 62
HI femi welcome to Bowen

In [5]:
# program that gives someone 3% discount on their loan if they are female, 4% discount
# if they are borrowing above 300k, 10% discount if they satisfy both condition.

name = input('Enter your name: ')
gender = input('Gender: ')
loan = float(input('loan: '))
time = float(input('time: '))
interest_rate = 4 

interest = (loan * interest_rate * time)/100

if gender == 'female' and loan > 300000:
    print(f'congrats {name}, you have{loan * 0.1} discount on your loan and your balance is: {loan *0.9}')
elif gender == 'female':
    print(f' Hi {name}, you have {loan * 0.03} discount on your loan and your balance is: {loan * 0.97}')
elif loan > 300000:
    print(f'congrats {name}, you have {loan * 0.04} discount on your loan and your balance is: {loan * 0.96}')
else:
    print(f'hi {name}, you are not qualified for a discount')

Enter your name: titi
Gender: female
loan: 300100
time: 1
congrats titi, you have30010.0 discount on your loan and your balance is: 270090.0

In [6]:



#ITERABLES (LISTS TUPLES AND DICTIONARIS)
# creating a list

students = ['femi','ugo','daniel','tosin','feyi']
even_num = list(range(2,21, 2))
odd_num = list(range(1,21,2))

# check data type
type(students)
# forward indexing
students[1]

# backward indexing
students[-4]

# slicing
students[:3]

# slicing
students[2:]

# slicing
students[1:3]

# slicing multidimensional list
staff = [['ugo',250,'male'],
['feyi',200,'male'],
['tola',100,'female']]

# access ugo's information
staff[0]

# access feyi's name
staff[1][0]

# list method and function
# counting elements in a list
len(students)
even_num
odd_num
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
zeta hy

list

In [37]:
#ITERABLES (LISTS TUPLES AND DICTIONARIS)
# creating a list

staff = ['tobi', 'winner', 'akin', 'aliu', 'mary']
even_num = list(range(2,21, 2))
odd_num = list(range(1,21,2))

#check datatype
type (staff)


#forwardindexing
staff[1:3]

staff.append('bola')
print(staff)

['tobi', 'winner', 'akin', 'aliu', 'mary', 'bola']

In [7]:
# slicing multidimensional list
staff =[['tobi', 13,'female', 'christianity'],
        ['winner', 23, 'female', 'christianity'],
        ['akin', 45, 'male', 'christianity'],
        ['aliu', 40, 'male', 'islam'], 
        ['mary', 38, 'female', 'christianity']]

#accessing mary info
staff[-1]

staff[1][0]

staff[-2][1]

staff[2][1:3]

staff[1][0:3]

# list method and function
# counting elements in a list
print(len(staff))

5

In [16]:
# creating a list

even_num = list(range(2,21, 2))
odd_num = list(range(1,21,2))

print(len(odd_num))

print(len(even_num))


# min, max, sum functions
print('sum', sum(odd_num))
print('average', sum(odd_num)/len(odd_num))

print('sum', sum(even_num))
print('minimumn', min(even_num))
print('maximum', max(even_num))
print('average', sum(even_num)/len(even_num))

10
10
sum 100
average 10.0
sum 110
minimumn 2
maximum 20
average 11.0

In [20]:
# assignment : pop, index, sorted, revered

#pop:remove and return

my_list = [1,2,3,4,5,6]
removed_item = my_list.pop(5)
print("Removed item:", removed_item)
print("Updated list:", my_list)

Removed item: 6
Updated list: [1, 2, 3, 4, 5]

In [22]:
# sorted 

my_list = [11,2,3,4,5,6,8,9,11,7,34,108,100]
sorted_list = sorted(my_list)
print(sorted_list)

[2, 3, 4, 5, 6, 7, 8, 9, 11, 11, 34, 100, 108]

In [36]:
#index

my_list = [1,2,3,4,5,6,8,9,141,7,34,108,100]
index = my_list.index(100)
print("index of value 100:", index)
print('sum', sum(my_list))
print(len(my_list))
print('average', sum(my_list)//len(my_list))

index of value 100: 12
sum 428
13
average 32

In [48]:
### dictionaries


staff = {
    'akin': 'accountant',
    'jide': 'driver',
    'bosun' : 'procurement'
}


# dictionary methods

# getting keys
staff.keys()
# getting values
staff.values()


# getting values
staff.values()

staff['bosun'] 

# adding new element
staff.update({'kwara':'ilorin'})

print(staff)

{'akin': 'accountant', 'jide': 'driver', 'bosun': 'procurement', 'kwara': 'ilorin'}

In [56]:
# exercise
# create a dictionary of staff names and age
# return all the names of staffs in your class
# return the minimum, maximum and average age of students in your class

staff = {
       'tobi': 13,
        'winner': 23,
        'akin': 45,
        'aliu': 40,
        'mary': 38
}

staff.keys()

staff.values()

age = list(staff.values())

print(f'Minimum = {min((age))}')

print(f'average = {sum((age))/len((age))}')

Minimum = 13
average = 31.8

In [63]:
for num in range(1, 5):
    print('God is good')

God is good
God is good
God is good
God is good

In [1]:
for num in range(1, 10):
    print('jah')

jah
jah
jah
jah
jah
jah
jah
jah
jah

In [11]:
# create a list of numbers between 50 and 100 that are divisible by 3

threes = []

for num in range(50, 101):
    if num % 3 == 0:
        threes.append(num)
    else:
        pass
    
threes

[51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]

In [2]:
# program that checks prime numbers

number = int(input('number: '))
for num in range(2, number):
    if num % num == 0:
        print(f'{number} is not prime')
        break
else:
    print(f'{number} is prime')

number: 3
3 is not prime

In [19]:
# a user validation program

staff = {'tobi':'abcd',
        'winner':'1234',
        'aliu':'xyz',
        'mary':'4433',
        'akin':'563'
        }

staff.keys()

staff.values()

name = input('enter your name: ')
if name not in staff.keys():
    print('access denied')
    decision = input('do you want to register: ')
    if decision == 'yes':
        password = input('chose a password: ')
        staff.update({name:password})
    else:
        pass
else:
    password = input('Enter password: ')
    if staff[name] == password:
        print(f'welcome {name}, have you heard from the HR today ')
    else:
        print('wrong password')

enter your name: mary
Enter password: 4433
welcome mary, have you heard from the HR today

In [11]:
# program that checks prime numbers

number = int(input('number: '))
for num in range(2, number):
    if number % num == 0:
        print(f'{number} is Not prime')
        break
    else:
        print(f'{number} is prime')

number: 42
42 is Not prime

In [25]:
import pandas as pd
import numpy as np

In [29]:
# how to create dataframes in pandas

# list of lists
staff_data =[
        ['tobi', 33,'female', 'christianity'],
        ['winner', 23, 'female', 'christianity'],
        ['akin', 45, 'male', 'christianity'],
        ['aliu', 40, 'male', 'islam'], 
        ['mary', 38, 'female', 'christianity']
]

staff_df = pd.DataFrame(data = staff_data, columns= ['name','age','gender','religion'])

staff_df

     name  age  gender      religion
0    tobi   33  female  christianity
1  winner   23  female  christianity
2    akin   45    male  christianity
3    aliu   40    male         islam
4    mary   38  female  christianity

In [31]:
# dictionaries
staff_dict = {
    'name': ['tobi', 'winner','akin','aliu','mary'],
    'gender': ['female', 'female','male', 'male','female'],
    'age': [33,23,45,40,38],
    'religion': ['christianity', 'christianity', 'christianity', 'islam','christianity']
}
staff_df2 = pd.DataFrame(staff_dict)

staff_df2

   age  gender    name      religion
0   33  female    tobi  christianity
1   23  female  winner  christianity
2   45    male    akin  christianity
3   40    male    aliu         islam
4   38  female    mary  christianity

In [34]:
# loading data from a local file
data = pd.read_csv('Hospital_General_Information.csv')

data

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL 35957\n"
1,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL 36278\n"
2,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL 35801\n"
3,20001,PROVIDENCE ALASKA MEDICAL CENTER,BOX 196604,ANCHORAGE,AK,99508,ANCHORAGE,9072123675,Acute Care Hospitals,Voluntary non-profit - Church,...,NaN,Below the National average,NaN,Below the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"BOX 196604\nANCHORAGE, AK 99508\n"
4,20018,YUKON KUSKOKWIM DELTA REG HOSPITAL,PO BOX 287,BETHEL,AK,99559,BETHEL,9075436300,Acute Care Hospitals,Tribal,...,NaN,Below the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 287\nBETHEL, AK 99559\n"
5,21309,KANAKANAK HOSPITAL,P O BOX 130,DILLINGHAM,AK,99576,DILLINGHAM,9078425201,Critical Access Hospitals,Voluntary non-profit - Private,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"P O BOX 130\nDILLINGHAM, AK 99576\n"
6,21310,MANIILAQ HEALTH CENTER,PO BOX 43,KOTZEBUE,AK,99752,NORTHWEST ARCTIC,9074423321,Critical Access Hospitals,Tribal,...,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,"PO BOX 43\nKOTZEBUE, AK 99752\n"
7,30071,FORT DEFIANCE INDIAN HOSPITAL,PO BOX 649,FORT DEFIANCE,AZ,86504,APACHE,9287298000,Acute Care Hospitals,Government - Federal,...,NaN,Not Available,Results are not available for this reporting p...,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 649\nFORT DEFIANCE, AZ 86504\n"
8,30073,TUBA CITY REGIONAL HEALTH CARE CORPORATION,PO BOX 600,TUBA CITY,AZ,86045,COCONINO,9282832501,Acute Care Hospitals,Voluntary non-profit - Other,...,NaN,Below the National average,NaN,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 600\nTUBA CITY, AZ 86045\n"
9,30074,SELLS INDIAN HEALTH SERVICE HOSPITAL,PO BOX 548,SELLS,AZ,85634,PIMA,5203837200,Acute Care Hospitals,Government - Federal,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 548\nSELLS, AZ 85634\n"
10,30077,SAN CARLOS APACHE HEALTHCARE,103 MEDICINE WAY ROAD,PERIDOT,AZ,85542,GILA,9284751200,Acute Care Hospitals,Government - Federal,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"103 MEDICINE WAY ROAD\nPERIDOT, AZ 85542\n"
11,30084,CHINLE COMPREHENSIVE HEALTH CARE FACILITY,"US HWY 191, HOSPITAL ROAD",CHINLE,AZ,86503,APACHE,9286747001,Acute Care Hospitals,Government - Federal,...,NaN,Same as the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"US HWY 191, HOSPITAL ROAD\nCHINLE, AZ 86503\n"
12,40007,CHI-ST VINCENT INFIRMARY,TWO ST VINCENT CIRCLE,LITTLE ROCK,AR,72205,PULASKI,5015523000,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Below the National average,NaN,Below the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"TWO ST VINCENT CIRCLE\nLITTLE ROCK, AR 72205\n"
13,31305,HOPI HEALTH CARE CENTER,"HIGHWAY 264, MILEPOST 388",POLACCA,AZ,86042,NAVAJO,9287376000,Critical Access Hospitals,Tribal,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"HIGHWAY 264, MILEPOST 388\nPOLACCA, AZ 86042\n"
14,31309,SAGE MEMORIAL HOSPITAL,STATE ROUTE 264 SOUTH 191 PO BOX 457,GANADO,AZ,86505,APACHE,9287554559,Critical Access Hospitals,Voluntary non-profit - Private,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"STATE ROUTE 264 SOUTH 191 PO BOX 457\nGANADO, ..."
15,41324,CHI ST VINCENT MORRILTON,#4 HOSPITAL DRIVE,MORRILTON,AR,72110,CONWAY,5019772300,Critical Access Hospitals,Voluntary non-profit - Church,...,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"#4 HOSPITAL DRIVE\nMORRILTON, AR 72110\n"
16,41328,CHICOT MEMORIAL MEDICAL CENTER,2729 SOUTH HIGHWAY 65 & 82,LAKE VILLAGE,AR,71653,CHICOT,8702655351,Critical Access Hospitals,Voluntary non-profit - Private,...,NaN,Above the National average,NaN,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,Below the National average,NaN,"2729 SOUTH HIGHWAY 65 &amp; 82\nLAKE VILLAGE, ..."
17,50054,SAN GORGONIO MEMORIAL HOSPITAL,600 NORTH HIGHLAND SPRINGS AVENUE,BANNING,CA,92220,RIVERSIDE,9518451121,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Below the National average,NaN,Same as the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,"600 NORTH HIGHLAND SPRINGS AVENUE\nBANNING, CA..."
18,50055,CALIFORNIA PACIFIC MEDICAL CTR - ST. LUKE'S CA...,3555 CESAR CHAVEZ STREET,SAN FRANCISCO,CA,94110,SAN FRANCISCO,4156416562,Acute Care Hospitals,Voluntary non-profit - Church,...,NaN,Below the National average,NaN,Same as the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"3555 CESAR CHAVEZ STREET\nSAN FRANCISCO, CA 94..."
19,50224,HOAG MEMORIAL HOSPITAL PRESBYTERIAN,ONE HOAG DRIVE,NEWPORT BEACH,CA,92663,ORANGE,9497644624,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Below the National average,NaN,"ONE HOAG DRIVE\nNEWPORT BEACH, CA 92663\n"
20,50309,SUTTER ROSEVILLE MEDICAL CENTER,ONE MEDICAL PLAZA,ROSEVILLE,CA,95661,PLACER,9167811000,Acute Care Hospitals,Voluntary non-profit - Other,...,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,Above the National average,NaN,"ONE MEDICAL PLAZA\nROSEVILLE, CA 95661\n"
21,50441,STANFORD HEALTH CARE,300 PASTEUR DRIVE,STANFORD,CA,94305,SANTA CLARA,6507235708,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Above the National average,NaN,Above the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"300 PASTEUR DRIVE\nSTANFORD, CA 94305\n"
22,50488,EDEN MEDICAL CENTER,20103 LAKE CHABOT ROAD,CASTRO VALLEY,CA,94546,ALAMEDA,5105371234,Acute Care Hospitals,Voluntary non-profit - Other,...,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"20103 LAKE CHABOT ROAD\nCASTRO VALLEY, CA 94546\n"
23,50567,MISSION HOSPITAL REGIONAL MED CENTER,27700 MEDICAL CENTER RD,MISSION VIEJO,CA,92691,ORANGE,9493641400,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Below the National average,NaN,Same as the National average,NaN,Below the National average,NaN,Below the National average,NaN,"27700 MEDICAL CENTER RD\nMISSION VIEJO, CA 926..."
24,50717,LAC/RANCHO LOS AMIGOS NATIONAL REHABILITATION ...,7601 EAST IMPERIAL HIGHWAY,DOWNEY,CA,90242,LOS ANGELES,5624017022,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Same as the National average,NaN,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"7601 EAST IMPERIAL HIGHWAY\nDOWNEY, CA 90242\n"
25,53306,CHILDREN'S HOSPITAL AT MISSION,"27700 MEDICAL CENTER RD, 5TH FLOOR",MISSION VIEJO,CA,92691,ORANGE,9493652408,Childrens,Voluntary non-profit - Private,...,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,"27700 MEDICAL CENTER RD, 5TH FLOOR\nMISSION VI..."
26,60104,ST ANTHONY NORTH HEALTH CAMPUS,14300 ORCHARD PARKWAY,WESTMINSTER,CO,80023,BROOMFIELD,3034303201,Acute Care Hospitals,Voluntary non-profit - Church,...,NaN,Same as the National average,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"14300 ORCHARD PARKWAY\nWESTMINSTER, CO 80023\n"
27,70029,BRISTOL HOSPITAL,BREWSTER RD,BRISTOL,CT,6010,HARTFORD,8605853000,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Above the National average,NaN,"BREWSTER RD\nBRISTOL, CT 06010\n"
28,80003,ST FRANCIS HOSPITAL,7TH AND CLAYTON STS,WILMINGTON,DE,19805,NEW CASTLE,3024214100,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Below the National average,NaN,Same as the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"7TH AND CLAYTON STS\nWILMINGTON, DE 19805\n"
29,100054,TWIN CITIES HOSPITAL,2190 HWY 85 N,NICEVILLE,FL,32578,OKALOOSA,8506784131,Acute Care Hospitals,Proprietary,...,NaN,Above the National average,NaN,Above the National average,NaN,Above the National average,NaN,Below the National average,NaN,"2190 HWY 85 N\nNICEVILLE, FL 32578\n"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4788,461302,MOAB REGIONAL HOSPITAL,450 WEST WILLIAMS WAY,MOAB,UT,84532,GRAND,4357193501,Critical Access Hospitals,Voluntary non-profit - Private,...,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,"450 WEST WILLIAMS WAY\nMOAB, UT 84532\n(38.574..."
4789,460007,CEDAR CITY HOSPITAL,1303 NORTH MAIN STREET,CEDAR CITY,UT,84721,IRON,4358685800,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"1303 NORTH MAIN STREET\nCEDAR CITY, UT 84721\n..."
4790,670072,HOPEBRIDGE HOSPITAL,5556 GASMER DRIVE,HOUSTON,TX,77035,HARRIS,7134222650,Acute Care Hospitals,Proprietary,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"5556 GASMER DRIVE\nHOUSTON, TX 77035\n(29.6511..."
4791,520206,AURORA MEDICAL CENTER,36500 AURORA DRIVE,SUMMIT,WI,53066,WAUKESHA,2624341000,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Above the National average,NaN,Same as the National average,NaN,Above the National average,NaN,Same as the National average,NaN,"36500 AURORA DRIVE\nSUMMIT, WI 53066\n(43.0637..."
4792,510071,BLUEFIELD REGIONAL MEDICAL CENTER,500 CHERRY ST,BLUEFIELD,WV,24701,MERCER,3043271100,Acute Care Hospitals,Proprietary,...,NaN,Below the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"500 CHERRY ST\nBLUEFIELD, WV 24701\n(37.257635..."
4793,461305,MILFORD VALLEY MEMORIAL HOSPITAL,850 NORTH MAIN STREET,MILFORD,UT,84751,BEAVER,4353872411,Critical Access Hospitals,Government - Hospital District or Authority,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"850 NORTH MAIN STREET\nMILFORD, UT 84751\n(38...."
4794,500051,OVERLAKE HOSPITAL MEDICAL CENTER,1035-116TH AVE NE,BELLEVUE,WA,98004,KING,4256885000,Acute Care Hospitals,Voluntary non-profit - Other,...,NaN,Same as the National average,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"1035-116TH AVE NE\nBELLEVUE, WA 98004\n(47.620..."
4795,670045,"COOK CHILDRENS NORTHEAST HOSPITAL, LLC",6316 PRECINCT LINE RD,HURST,TX,76054,TARRANT,8176052500,Acute Care Hospitals,Physician,...,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,"6316 PRECINCT LINE RD\nHURST, TX 76054\n(32.86..."
4796,451347,COLEMAN COUNTY MEDICAL CENTER COMPANY,310 SOUTH PECOS STREET,COLEMAN,TX,76834,COLEMAN,3256252135,Critical Access Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"310 SOUTH PECOS STREET\nCOLEMAN, TX 76834\n(31..."
4797,503300,SEATTLE CHILDREN'S HOSPITAL,"4800 SAND POINT WAY NE, PO BOX C-5371",SEATTLE,WA,98105,KING,2069872000,Childrens,Voluntary non-profit - Private,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"4800 SAND POINT WAY NE, PO BOX C-5371\nSEATTLE..."
4798,450184,MEMORIAL HERMANN HOSPITAL SYSTEM,1635 NORTH LOOP WEST,HOUSTON,TX,77008,HARRIS,7134486796,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,Below the National average,NaN,"1635 NORTH LOOP WEST\nHOUSTON, TX 77008\n(29.8..."
4799,453308,OUR CHILDRENS HOUSE,8 PRESTIGE CIRCLE 101,ALLEN,TX,75002,COLLIN,2148284747,Childrens,Voluntary non-profit - Church,...,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,"8 PRESTIGE CIRCLE 101\nALLEN, TX 75002\n(33.09..."
4800,670025,THE HEART HOSPITAL BAYLOR PLANO,1100 ALLIED DRIVE,PLANO,TX,75093,COLLIN,4698143278,Acute Care Hospitals,Proprietary,...,NaN,Above the National average,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"1100 ALLIED DRIVE\nPLANO, TX 75093\n(33.015252..."
4801,440153,TENNOVA HEALTHCARE-NEWPORT MEDICAL CENTER,435 2ND ST,NEWPORT,TN,37821,COCKE,4236252200,Acute Care Hospitals,Voluntary non-profit - Church,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Above the National average,NaN,Same as the National average,NaN,"435 2ND ST\nNEWPORT, TN 37821\n(35.964777, -83..."
4802,510047,FAIRMONT REGIONAL MEDICAL CENTER,1325 LOCUST AVENUE,FAIRMONT,WV,26554,MARION,3043677100,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Below the National average,NaN,Above the National average,NaN,Above the National average,NaN,Below the National average,NaN,"1325 LOCUST AVENUE\nFAIRMONT, WV 26554\n(39.48..."
4803,510008,BERKELEY MEDICAL CENTER,2500 HOSPITAL DRIVE,MARTINSBURG,WV,25401,BERKELEY,3042641000,Acute Care Hospitals,Voluntary non-profit - Other,...,NaN,Below the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"2500 HOSPITAL DRIVE\nMARTINSBURG, WV 25401\n(3..."
4804,501318,OTHELLO COMMUNITY HOSPITAL,315 NORTH 14TH AVENUE,OTHELLO,WA,99344,ADAMS,5094882636,Critical Access Hospitals,Government - Hospital District or Authority,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"315 NORTH 14TH AVENUE\nOTHELLO, WA 99344\n(46...."
4805,450718,ROUND ROCK MEDICAL CENTER,2400 ROUND ROCK AVE,ROUND ROCK,TX,78681,WILLIAMSON,5123411000,Acute Care Hospitals,Voluntary non-profit - Other,...,NaN,Same as the National average,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"2400 ROUND ROCK AVE\nROUND ROCK, TX 78681\n(30..."
4806,450044,UT SOUTHWESTERN UNIVERSITY HOSPITAL,6201 HARRY HINES BLVD,DALLAS,TX,75390,DALLAS,2146335555,Acute Care Hospitals,Government - State,...,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"6201 HARRY HINES BLVD\nDALLAS, TX 75390\n(32.8..."

In [6]:
import mysql_.connector
from mysql.connector import Error 
from IPython.display import clear_output


def db_connect(user_name, host_name, db_name, password):
    connection = None
    try:
        connection = mysql.connector.connect(
            user = user_name,
            host = host_name,
            database = db_name,
            passwd = password
        )
        print(f'connected to {db_name} successfully')
    except Error as err:
        print(f"Error: {err}")
    
    return connection

ModuleNotFoundError: No module named 'mysql'

In [ ]:
pw = input('password: ')
clear_output()

connection = db_connect(user_name='root',host_name='localhost',
                        db_name='northwind',password=pw)

In [ ]:
def read_query(connection, query):
    result = None
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        result = cursor.fetchall()
    except Error as err:
        print(f"Error: {err}")
    
    return result

In [ ]:
query_1 = '''

select orderid, freight, shipcountry
from orders
limit 50;
'''

data = read_query(connection=connection, query= query_1)
data

In [ ]:
# converting to dataframe
data_list = []

for row in data:
    row = list(row)
    data_list.append(row)

columns = ['orderid','freight','shipcountry']

order_df = pd.DataFrame(data=data_list, columns=columns)

order_df

In [9]:
#name = input('enter name: ')
def count_vowels(name):
    count = []
    vowel = ['a','e','i','o','u']
    for letter in name:
        if letter in vowel:
            count.append(letter)
        else:
            pass
    return len(count)

count_vowels('awele')

3

In [10]:
def count_vowels(name):
    count = []
    vowel = ['a','e','i','o','u']
    for letter in name:
        if letter in vowel and letter not in count:
            count.append(letter)
        else:
            pass
    return len(count)

count_vowels('awele')

2

In [18]:
def get_dollar(naira, rate):
    try:
        dollar = naira / rate
    except ZeroDivisionError:
        return (f'You no wise') 
    
    return dollar


get_dollar(2000, 800)

2.5

In [16]:
import pandas as pd
import numpy as np

In [2]:
import mysql.connector
from mysql.connector import Error 
from IPython.display import clear_output


def db_connect(user_name, host_name, db_name, password):
    connection = None
    try:
        connection = mysql.connector.connect(
            user = user_name,
            host = host_name,
            database = db_name,
            passwd = password
        )
        print(f'connected to {db_name} successfully')
    except Error as err:
        print(f"Error: {err}")
    
    return connection

In [3]:
pw = input('password: ')
clear_output()

connection = db_connect(user_name='root',host_name='localhost',
                        db_name='northwind',password=pw)

connected to northwind successfully

In [5]:
def read_query(connection, query):
    result = None
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        result = cursor.fetchall()
    except Error as err:
        print(f"Error: {err}")
    
    return result

In [6]:
query_1 = '''

select orderid, freight, shipcountry
from orders
limit 50;
'''

data = read_query(connection=connection, query= query_1)
data

[(10248, Decimal('32.3800'), 'France'),
 (10249, Decimal('11.6100'), 'Germany'),
 (10250, Decimal('65.8300'), 'Brazil'),
 (10251, Decimal('41.3400'), 'France'),
 (10252, Decimal('51.3000'), 'Belgium'),
 (10253, Decimal('58.1700'), 'Brazil'),
 (10254, Decimal('22.9800'), 'Switzerland'),
 (10255, Decimal('148.3300'), 'Switzerland'),
 (10256, Decimal('13.9700'), 'Brazil'),
 (10257, Decimal('81.9100'), 'Venezuela'),
 (10258, Decimal('140.5100'), 'Austria'),
 (10259, Decimal('3.2500'), 'Mexico'),
 (10260, Decimal('55.0900'), 'Germany'),
 (10261, Decimal('3.0500'), 'Brazil'),
 (10262, Decimal('48.2900'), 'USA'),
 (10263, Decimal('146.0600'), 'Austria'),
 (10264, Decimal('3.6700'), 'Sweden'),
 (10265, Decimal('55.2800'), 'France'),
 (10266, Decimal('25.7300'), 'Finland'),
 (10267, Decimal('208.5800'), 'Germany'),
 (10268, Decimal('66.2900'), 'Venezuela'),
 (10269, Decimal('4.5600'), 'USA'),
 (10270, Decimal('136.5400'), 'Finland'),
 (10271, Decimal('4.5400'), 'USA'),
 (10272, Decimal('98.0300'), 'USA'),
 (10273, Decimal('76.0700'), 'Germany'),
 (10274, Decimal('6.0100'), 'France'),
 (10275, Decimal('26.9300'), 'Italy'),
 (10276, Decimal('13.8400'), 'Mexico'),
 (10277, Decimal('125.7700'), 'Germany'),
 (10278, Decimal('92.6900'), 'Sweden'),
 (10279, Decimal('25.8300'), 'Germany'),
 (10280, Decimal('8.9800'), 'Sweden'),
 (10281, Decimal('2.9400'), 'Spain'),
 (10282, Decimal('12.6900'), 'Spain'),
 (10283, Decimal('84.8100'), 'Venezuela'),
 (10284, Decimal('76.5600'), 'Germany'),
 (10285, Decimal('76.8300'), 'Germany'),
 (10286, Decimal('229.2400'), 'Germany'),
 (10287, Decimal('12.7600'), 'Brazil'),
 (10288, Decimal('7.4500'), 'Italy'),
 (10289, Decimal('22.7700'), 'UK'),
 (10290, Decimal('79.7000'), 'Brazil'),
 (10291, Decimal('6.4000'), 'Brazil'),
 (10292, Decimal('1.3500'), 'Brazil'),
 (10293, Decimal('21.1800'), 'Mexico'),
 (10294, Decimal('147.2600'), 'USA'),
 (10295, Decimal('1.1500'), 'France'),
 (10296, Decimal('0.1200'), 'Venezuela'),
 (10297, Decimal('5.7400'), 'France')]

In [17]:
# converting to dataframe
data_list = []

for row in data:
    row = list(row)
    data_list.append(row)

columns = ['orderid','freight','shipcountry']

order_df = pd.DataFrame(data=data_list, columns=columns)

order_df

    orderid   freight  shipcountry
0     10248   32.3800       France
1     10249   11.6100      Germany
2     10250   65.8300       Brazil
3     10251   41.3400       France
4     10252   51.3000      Belgium
5     10253   58.1700       Brazil
6     10254   22.9800  Switzerland
7     10255  148.3300  Switzerland
8     10256   13.9700       Brazil
9     10257   81.9100    Venezuela
10    10258  140.5100      Austria
11    10259    3.2500       Mexico
12    10260   55.0900      Germany
13    10261    3.0500       Brazil
14    10262   48.2900          USA
15    10263  146.0600      Austria
16    10264    3.6700       Sweden
17    10265   55.2800       France
18    10266   25.7300      Finland
19    10267  208.5800      Germany
20    10268   66.2900    Venezuela
21    10269    4.5600          USA
22    10270  136.5400      Finland
23    10271    4.5400          USA
24    10272   98.0300          USA
25    10273   76.0700      Germany
26    10274    6.0100       France
27    10275   26.9300        Italy
28    10276   13.8400       Mexico
29    10277  125.7700      Germany
30    10278   92.6900       Sweden
31    10279   25.8300      Germany
32    10280    8.9800       Sweden
33    10281    2.9400        Spain
34    10282   12.6900        Spain
35    10283   84.8100    Venezuela
36    10284   76.5600      Germany
37    10285   76.8300      Germany
38    10286  229.2400      Germany
39    10287   12.7600       Brazil
40    10288    7.4500        Italy
41    10289   22.7700           UK
42    10290   79.7000       Brazil
43    10291    6.4000       Brazil
44    10292    1.3500       Brazil
45    10293   21.1800       Mexico
46    10294  147.2600          USA
47    10295    1.1500       France
48    10296    0.1200    Venezuela
49    10297    5.7400       France